apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hcp-api-gateway
  namespace: hcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcp-api-gateway
  template:
    metadata:
      labels:
        app: hcp-api-gateway
    spec:
      containers:
        - name: hcp-api-gateway
          image: rudals4549/hcp-api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          envFrom:
            - configMapRef:
                name: hcp-api-gateway-config
            - secretRef:
                name: hcp-api-gateway-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=50 -XX:InitialRAMPercentage=20"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 5
  strategy:
    blueGreen:
      activeService: hcp-api-gateway-svc
      previewService: hcp-api-gateway-preview-svc
      autoPromotionEnabled: false
      previewReplicaCount: 1
      scaleDownDelaySeconds: 30
