apiVersion: v1
kind: Secret
metadata:
  name: hcp-mysql-secret
  namespace: hcp
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD
  MYSQL_DATABASE: MYSQL_DATABASE


