apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hcp-mysql
  namespace: hcp
spec:
  serviceName: hcp-mysql-svc
  replicas: 1
  selector:
    matchLabels:
      app: hcp-mysql
  template:
    metadata:
      labels:
        app: hcp-mysql
    spec:
      containers:
        - name: hcp-mysql
          image: mysql:8.0.33
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - secretRef:
                name: hcp-mysql-secret
          env:
            - name: TZ
              value: Asia/Seoul
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
