apiVersion: v1
kind: Service
metadata:
  name: hcp-redis-svc
  namespace: hcp
spec:
  selector:
    app: hcp-redis
  ports:
    - name: hcp-redis
      port: 6379
      targetPort: 6379
  type: ClusterIP