apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcp-orchestrator-worker
  namespace: hcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcp-orchestrator-worker
  template:
    metadata:
      labels:
        app: hcp-orchestrator-worker
    spec:
      serviceAccountName: hcp-orchestrator-worker
      containers:
        - name: hcp-orchestrator-worker
          image: rudals4549/hcp-orchestrator-worker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: hcp-orchestrator-worker-config
            - secretRef:
                name: hcp-orchestrator-worker-secret

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 5
