apiVersion: v1
kind: Service
metadata:
  name: hcp-orchestrator-worker-svc
  namespace: hcp
  labels:
    app: hcp-orchestrator-worker
spec:
  selector:
    app: hcp-orchestrator-worker
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP