apiVersion: v1
kind: Service
metadata:
  name: hcp-kafka-svc
  namespace: hcp
spec:
  selector:
    app: hcp-kafka
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
  type: ClusterIP