apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kookyungmin/hcp-k8s-manifest.git
    targetRevision: main
    path: overlays/dev/api-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: hcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true