apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcp-compute-service
  namespace: hcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcp-compute-service
  template:
    metadata:
      labels:
        app: hcp-compute-service
    spec:
      containers:
        - name: hcp-compute-service
          image: rudals4549/hcp-compute-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: hcp-compute-service-config
            - secretRef:
                name: hcp-compute-service-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=50 -XX:InitialRAMPercentage=20"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 10
