apiVersion: v1
kind: Service
metadata:
  name: hcp-compute-service-svc
  namespace: hcp
spec:
  selector:
    app: hcp-compute-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP